// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: observation.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Constellation int32

const (
	Constellation_GPS     Constellation = 0
	Constellation_GLONASS Constellation = 1
	Constellation_GALILEO Constellation = 2
	Constellation_SBAS    Constellation = 3
	Constellation_QZSS    Constellation = 4
	Constellation_BEIDOU  Constellation = 5
)

// Enum value maps for Constellation.
var (
	Constellation_name = map[int32]string{
		0: "GPS",
		1: "GLONASS",
		2: "GALILEO",
		3: "SBAS",
		4: "QZSS",
		5: "BEIDOU",
	}
	Constellation_value = map[string]int32{
		"GPS":     0,
		"GLONASS": 1,
		"GALILEO": 2,
		"SBAS":    3,
		"QZSS":    4,
		"BEIDOU":  5,
	}
)

func (x Constellation) Enum() *Constellation {
	p := new(Constellation)
	*p = x
	return p
}

func (x Constellation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Constellation) Descriptor() protoreflect.EnumDescriptor {
	return file_observation_proto_enumTypes[0].Descriptor()
}

func (Constellation) Type() protoreflect.EnumType {
	return &file_observation_proto_enumTypes[0]
}

func (x Constellation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Constellation.Descriptor instead.
func (Constellation) EnumDescriptor() ([]byte, []int) {
	return file_observation_proto_rawDescGZIP(), []int{0}
}

type SatelliteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SatelliteId uint32 `protobuf:"varint,1,opt,name=satelliteId,proto3" json:"satelliteId,omitempty"`
	// TODO: Consider putting satelliteID in SignalData and removing SatelliteData
	SignalData *SignalData `protobuf:"bytes,2,opt,name=signalData,proto3" json:"signalData,omitempty"` // Ignoring Extended
}

func (x *SatelliteData) Reset() {
	*x = SatelliteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatelliteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteData) ProtoMessage() {}

func (x *SatelliteData) ProtoReflect() protoreflect.Message {
	mi := &file_observation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteData.ProtoReflect.Descriptor instead.
func (*SatelliteData) Descriptor() ([]byte, []int) {
	return file_observation_proto_rawDescGZIP(), []int{0}
}

func (x *SatelliteData) GetSatelliteId() uint32 {
	if x != nil {
		return x.SatelliteId
	}
	return 0
}

func (x *SatelliteData) GetSignalData() *SignalData {
	if x != nil {
		return x.SignalData
	}
	return nil
}

type SignalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Band           string  `protobuf:"bytes,1,opt,name=band,proto3" json:"band,omitempty"`
	Frequency      string  `protobuf:"bytes,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Pseudorange    float32 `protobuf:"fixed32,3,opt,name=pseudorange,proto3" json:"pseudorange,omitempty"`
	PhaseRange     float32 `protobuf:"fixed32,4,opt,name=phaseRange,proto3" json:"phaseRange,omitempty"`
	PhaseRangeLock uint32  `protobuf:"varint,5,opt,name=phaseRangeLock,proto3" json:"phaseRangeLock,omitempty"`
	HalfCycle      bool    `protobuf:"varint,6,opt,name=halfCycle,proto3" json:"halfCycle,omitempty"`
	Snr            float32 `protobuf:"fixed32,7,opt,name=snr,proto3" json:"snr,omitempty"`
	PhaseRangeRate float32 `protobuf:"fixed32,8,opt,name=phaseRangeRate,proto3" json:"phaseRangeRate,omitempty"`
}

func (x *SignalData) Reset() {
	*x = SignalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalData) ProtoMessage() {}

func (x *SignalData) ProtoReflect() protoreflect.Message {
	mi := &file_observation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalData.ProtoReflect.Descriptor instead.
func (*SignalData) Descriptor() ([]byte, []int) {
	return file_observation_proto_rawDescGZIP(), []int{1}
}

func (x *SignalData) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

func (x *SignalData) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *SignalData) GetPseudorange() float32 {
	if x != nil {
		return x.Pseudorange
	}
	return 0
}

func (x *SignalData) GetPhaseRange() float32 {
	if x != nil {
		return x.PhaseRange
	}
	return 0
}

func (x *SignalData) GetPhaseRangeLock() uint32 {
	if x != nil {
		return x.PhaseRangeLock
	}
	return 0
}

func (x *SignalData) GetHalfCycle() bool {
	if x != nil {
		return x.HalfCycle
	}
	return false
}

func (x *SignalData) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *SignalData) GetPhaseRangeRate() float32 {
	if x != nil {
		return x.PhaseRangeRate
	}
	return 0
}

type ObservationSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch              *timestamp.Timestamp `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ReferenceStationId string               `protobuf:"bytes,2,opt,name=referenceStationId,proto3" json:"referenceStationId,omitempty"`
	Constellation      Constellation        `protobuf:"varint,3,opt,name=constellation,proto3,enum=data.Constellation" json:"constellation,omitempty"`
	// Ignoring Clock Indicators
	SatelliteData *SatelliteData `protobuf:"bytes,4,opt,name=satelliteData,proto3" json:"satelliteData,omitempty"`
}

func (x *ObservationSet) Reset() {
	*x = ObservationSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObservationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationSet) ProtoMessage() {}

func (x *ObservationSet) ProtoReflect() protoreflect.Message {
	mi := &file_observation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationSet.ProtoReflect.Descriptor instead.
func (*ObservationSet) Descriptor() ([]byte, []int) {
	return file_observation_proto_rawDescGZIP(), []int{2}
}

func (x *ObservationSet) GetEpoch() *timestamp.Timestamp {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *ObservationSet) GetReferenceStationId() string {
	if x != nil {
		return x.ReferenceStationId
	}
	return ""
}

func (x *ObservationSet) GetConstellation() Constellation {
	if x != nil {
		return x.Constellation
	}
	return Constellation_GPS
}

func (x *ObservationSet) GetSatelliteData() *SatelliteData {
	if x != nil {
		return x.SatelliteData
	}
	return nil
}

var File_observation_proto protoreflect.FileDescriptor

var file_observation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0d, 0x53, 0x61,
	0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x80, 0x02, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61,
	0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x68, 0x61, 0x73, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x70, 0x68, 0x61, 0x73, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x68, 0x61, 0x73, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x4c, 0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61,
	0x6c, 0x66, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68,
	0x61, 0x6c, 0x66, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6e, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x73, 0x6e, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x68,
	0x61, 0x73, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0e, 0x70, 0x68, 0x61, 0x73, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61,
	0x74, 0x65, 0x22, 0xe8, 0x01, 0x0a, 0x0e, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0d, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0d,
	0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x52, 0x0a,
	0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07,
	0x0a, 0x03, 0x47, 0x50, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x4c, 0x4f, 0x4e, 0x41,
	0x53, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x41, 0x4c, 0x49, 0x4c, 0x45, 0x4f, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x42, 0x41, 0x53, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x51,
	0x5a, 0x53, 0x53, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x45, 0x49, 0x44, 0x4f, 0x55, 0x10,
	0x05, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x2d, 0x67, 0x6e, 0x73, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_observation_proto_rawDescOnce sync.Once
	file_observation_proto_rawDescData = file_observation_proto_rawDesc
)

func file_observation_proto_rawDescGZIP() []byte {
	file_observation_proto_rawDescOnce.Do(func() {
		file_observation_proto_rawDescData = protoimpl.X.CompressGZIP(file_observation_proto_rawDescData)
	})
	return file_observation_proto_rawDescData
}

var file_observation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_observation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_observation_proto_goTypes = []interface{}{
	(Constellation)(0),          // 0: data.Constellation
	(*SatelliteData)(nil),       // 1: data.SatelliteData
	(*SignalData)(nil),          // 2: data.SignalData
	(*ObservationSet)(nil),      // 3: data.ObservationSet
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_observation_proto_depIdxs = []int32{
	2, // 0: data.SatelliteData.signalData:type_name -> data.SignalData
	4, // 1: data.ObservationSet.epoch:type_name -> google.protobuf.Timestamp
	0, // 2: data.ObservationSet.constellation:type_name -> data.Constellation
	1, // 3: data.ObservationSet.satelliteData:type_name -> data.SatelliteData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_observation_proto_init() }
func file_observation_proto_init() {
	if File_observation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_observation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SatelliteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObservationSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_observation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_observation_proto_goTypes,
		DependencyIndexes: file_observation_proto_depIdxs,
		EnumInfos:         file_observation_proto_enumTypes,
		MessageInfos:      file_observation_proto_msgTypes,
	}.Build()
	File_observation_proto = out.File
	file_observation_proto_rawDesc = nil
	file_observation_proto_goTypes = nil
	file_observation_proto_depIdxs = nil
}
